version: '2'

services:
  ocomis-logging-elasticsearch:
    image: blutner/ocomis-logging-elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  ocomis-logging-logstash:
    image: blutner/ocomis-logging-logstash:latest
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    links:
      - ocomis-logging-elasticsearch

  ocomis-logging-kibana:
    image: blutner/ocomis-logging-kibana:latest
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    links:
      - ocomis-logging-elasticsearch
